#!/usr/bin/env bash
set -euo pipefail

# Cloudflare Tunnel setup script for Omega Document Creator.
# Run once to create and configure a new tunnel.
#
# Prerequisites:
#   - cloudflared installed: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/
#   - Cloudflare account with a domain
#   - kubectl not required (this uses cloudflared directly)
#
# Usage:
#   1. Authenticate: cloudflared tunnel login
#   2. Run: ./infra/cloudflared/setup-tunnel.sh
#   3. Follow prompts for hostnames
#   4. Copy the generated config.yaml and credentials file

if ! command -v cloudflared >/dev/null 2>&1; then
    echo "cloudflared is not installed. Install it first:"
    echo "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
    exit 1
fi

CLOUDFLARED_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$CLOUDFLARED_DIR/config.yaml"
CREDENTIALS_DIR="$CLOUDFLARED_DIR"

echo "=== Omega Document Creator — Cloudflare Tunnel Setup ==="
echo ""

# Prompt for tunnel name
read -r -p "Tunnel name [omega-tunnel]: " TUNNEL_NAME
TUNNEL_NAME="${TUNNEL_NAME:-omega-tunnel}"

# Prompt for hostnames
read -r -p "API hostname (e.g., omega-api.yourdomain.com): " API_HOSTNAME
read -r -p "Frontend hostname (e.g., omega.yourdomain.com): " FRONTEND_HOSTNAME

echo ""
echo "Creating tunnel '$TUNNEL_NAME'..."

# Create tunnel
TUNNEL_OUTPUT=$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)
TUNNEL_ID=$(echo "$TUNNEL_OUTPUT" | grep -oP 'Created tunnel \K[a-f0-9\-]+' || true)

if [ -z "$TUNNEL_ID" ]; then
    echo "Error: Could not extract tunnel ID from cloudflared output."
    echo "Output was: $TUNNEL_OUTPUT"
    echo "Check that cloudflared is authenticated and the tunnel name is unique."
    exit 1
fi

echo "Tunnel created with ID: $TUNNEL_ID"

# The credentials file is created by cloudflared in ~/.cloudflared/
CREDS_SRC="$HOME/.cloudflared/${TUNNEL_ID}.json"
if [ -f "$CREDS_SRC" ]; then
    cp "$CREDS_SRC" "$CREDENTIALS_DIR/${TUNNEL_ID}.json"
    echo "Credentials file copied to: $CREDENTIALS_DIR/${TUNNEL_ID}.json"
else
    echo "Warning: Credentials file not found at $CREDS_SRC"
    echo "Check ~/.cloudflared/ for the file and copy it manually."
fi

# Generate config.yaml
cat > "$CONFIG_FILE" <<EOF
# Cloudflare Tunnel configuration for Omega Document Creator.
# Generated by setup-tunnel.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/${TUNNEL_ID}.json

ingress:
  - hostname: ${API_HOSTNAME}
    service: http://api:8000
  - hostname: ${FRONTEND_HOSTNAME}
    service: http://frontend:3000

  # Catch-all: deny everything else
  - service: http_status:404
EOF

echo ""
echo "Config written to: $CONFIG_FILE"

# Create DNS records
echo ""
echo "Creating DNS records..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$API_HOSTNAME" 2>&1 || echo "Warning: DNS record for $API_HOSTNAME may already exist"
cloudflared tunnel route dns "$TUNNEL_NAME" "$FRONTEND_HOSTNAME" 2>&1 || echo "Warning: DNS record for $FRONTEND_HOSTNAME may already exist"

echo ""
echo "=== Setup complete ==="
echo ""
echo "Tunnel ID: $TUNNEL_ID"
echo "Credentials: $CREDENTIALS_DIR/${TUNNEL_ID}.json"
echo "Config: $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  1. Ensure $CREDENTIALS_DIR/${TUNNEL_ID}.json is NOT committed to git (already in .gitignore)"
echo "  2. Set these in .env:"
echo "       ENVIRONMENT=production"
echo "       REMOTE_ACCESS_MODE=remote"
echo "       CORS_ORIGINS=https://${FRONTEND_HOSTNAME},https://${API_HOSTNAME}"
echo "       CSRF_TRUSTED_ORIGINS=https://${FRONTEND_HOSTNAME},https://${API_HOSTNAME}"
echo "       APP_URL=https://${FRONTEND_HOSTNAME}"
echo "       TRUSTED_PROXY_COUNT=1"
echo "       COOKIE_SECURE=true"
echo "       SESSION_SECRET=<generate-a-strong-random-secret>"
echo "  3. (Optional) run: cloudflared tunnel run $TUNNEL_NAME &"
echo "  4. (Docker) run: docker compose -f infra/docker/compose.yaml up"
echo "     To include the cloudflared sidecar, uncomment the cloudflared service block in compose.yaml"
echo "     and ensure ${TUNNEL_ID}.json is at infra/cloudflared/${TUNNEL_ID}.json"
echo ""
echo "Test: curl -H 'Host: $API_HOSTNAME' http://localhost:8000/ready"
